Update launcher

diff --git a/launcher b/launcher
--- a/launcher
+++ b/launcher
@@ -20,11 +20,6 @@ usage () {
   echo "    --docker-args              Extra arguments to pass when running docker"
   echo "    --skip-mac-address         Don't assign a mac address"
   echo "    --run-image                Override the image used for running the container"
-  echo "    uwu                        Sends your IP Address to Pokimane"
-  echo "    OwO what's this?           Summons every furry in your area"
-  echo "    --free-robux               Adds free robux to your Discourse install."
-  echo "    --phon-number              Prints out your crushes' phone number."
-  echo "    --doxx                     Doxxes you."
   exit 1
 }
 
@@ -45,18 +40,6 @@ user_run_image=""
 if [[ $command == "run" ]]; then
   run_command=$3
 fi
-echo "-----------------------------------------// LAUNCHER \\-----------------------------------------"
-echo 'WARN: Today is opposite day! Make sure to input "N" when you want to input Y!'
-
-echo "
-   ___          ___  
-  / _ \__ __ __/ _ \ 
- | (_) \ V  V / (_) |
-  \___/ \_/\_/ \___/ 
-                     
- DISCOURSE ANIME EDITION
-        2013.
-"
 
 while [ ${#} -gt 0 ]; do
   case "${1}" in
@@ -92,7 +75,7 @@ re='[[:upper:]/ !@#$%^&*()+~`=]'
 if [[ $config =~ $re ]];
   then
     echo
-    echo "Silly goose, '$config' has to be lowercase! Correct and rerun $0."
+    echo "ERROR: Config name '$config' must not contain upper case characters, spaces or special characters. Correct config name and rerun $0."
     echo
     exit 1
 fi
@@ -108,7 +91,7 @@ git_rec_version='1.8.0'
 config_file=containers/"$config".yml
 cidbootstrap=cids/"$config"_bootstrap.cid
 local_discourse=local_discourse
-image="discourse/base:2.0.20220720-0049"
+image=samsaffron/discourse:1.0.6
 docker_path=`which docker.io 2> /dev/null || which docker`
 git_path=`which git`
 
@@ -145,8 +128,8 @@ fatal () {
 }
 
 install_docker() {
-  echo "lol you gotta install docker dudeski. not cool bro 🤙🤙🤙🤙🤘🤘🤘🤘"
-  echo "if you gotta, then here you go bro. https://docs.docker.com/installation/  have a gnarly day"
+  echo "Docker is not installed, you will need to install Docker in order to run Launcher"
+  echo "See https://docs.docker.com/installation/"
   exit 1
 }
 
@@ -172,8 +155,8 @@ check_prereqs() {
 
   # 2. running an approved storage driver?
   if ! $docker_path info 2> /dev/null | egrep -q 'Storage Driver: (btrfs|aufs|zfs|overlay2)$'; then
-    echo "dude. not cool. your docker is old or broken. not gnarly."
-    echo "OwO! It awso may be ywor Fiwlesystem. Pwoceed with cawshun!!"
+    echo "Your Docker installation is not using a supported storage driver.  If we were to proceed you may have a broken install."
+    echo "overlay2 is the recommended storage driver, although zfs and aufs may work as well."
     echo "Other storage drivers are known to be problematic."
     echo "You can tell what filesystem you are using by running \"docker info\" and looking at the 'Storage Driver' line."
     echo
@@ -188,32 +171,32 @@ check_prereqs() {
 
   # At least minimum docker version
   if compare_version "${docker_min_version}" "${test}"; then
-    echo "Ewwor: Docker version ${test} not supported, please upgrade to at least ${docker_min_version}, or recommended ${docker_rec_version}. QwQ"
+    echo "ERROR: Docker version ${test} not supported, please upgrade to at least ${docker_min_version}, or recommended ${docker_rec_version}"
     exit 1
   fi
 
   # Recommend newer docker version
   if compare_version "${docker_rec_version}" "${test}"; then
-    echo "OwO!: Dwoker version ${test} deprecated, recommend upgrade to ${docker_rec_version} or newer."
+    echo "WARNING: Docker version ${test} deprecated, recommend upgrade to ${docker_rec_version} or newer."
   fi
 
   arm=false
   case $(uname -m) in
     armv7l)
-      echo "Ewwor: 32 bit awm is not supported senpai! pwetty pwease get a better sewver."
+      echo "ERROR: 32bit arm is not supported. Check if your hardware support arm64, which is supported in experimental capacity."
       exit 1
       ;;
     aarch64 | arm64)
-      echo "rawr!: suppowrt for awrch is expewimental at the moment. pwease wepowrt any pwobwems at https://meta.discourse.org/tag/arm "
+      echo "WARNING: Support for aarch64 is experimental at the moment. Please report any problems at https://meta.discourse.org/tag/arm "
       image="discourse/base:aarch64"
       arm=true
-      read -n 1 -s -r -p "pwease press a button to call pokimane"
+      read -n 1 -s -r -p "Press any key to continue"
       ;;
     x86_64)
-      echo "x86_64 awrch detected."
+      echo "x86_64 arch detected."
       ;;
     *)
-      echo "OwO whats this? an ewwor?? unknown awrch detected."
+      echo "ERROR: unknown arch detected."
       exit 1
       ;;
   esac
@@ -224,9 +207,14 @@ check_prereqs() {
 
   # arm experimental support is on a fixed tag, always pull
   if [ -z "$test" ] || [ $arm = true ]; then
-    echo "uwu"
     echo
-    echo "oh noes!! sowwy discourse wasn't for you!!"
+    echo "WARNING: We are about to start downloading the Discourse base image"
+    echo "This process may take anywhere between a few minutes to an hour, depending on your network speed"
+    echo
+    echo "Please be patient"
+    echo
+
+    pull_image
   fi
 
   # 5. running recommended git version
@@ -235,21 +223,21 @@ check_prereqs() {
 
   # At least minimum version
   if compare_version "${git_min_version}" "${test}"; then
-    echo "ewwor!! git versioun ${test} not suppowrted, pwease upgwade to at least ${git_min_version}, or recommended ${git_rec_version}"
+    echo "ERROR: Git version ${test} not supported, please upgrade to at least ${git_min_version}, or recommended ${git_rec_version}"
     exit 1
   fi
 
   # Recommend best version
   if compare_version "${git_rec_version}" "${test}"; then
-    echo "rawr!: git vewsion ${test} depwcated, recommend upgrade to ${git_rec_version} or newer."
+    echo "WARNING: Git version ${test} deprecated, recommend upgrade to ${git_rec_version} or newer."
   fi
 
   # 6. able to attach stderr / out / tty
   test=`$docker_path run $user_args -i --rm -a stdout -a stderr $image echo working`
   if [[ "$test" =~ "working" ]] ; then : ; else
-    echo "rawr! dowkr isn't operating cowwect qwq"
+    echo "Your Docker installation is not working correctly"
     echo
-    echo "see: https://meta.discourse.org/t/docker-error-on-bootstrap/13657/18?u=pixlz"
+    echo "See: https://meta.discourse.org/t/docker-error-on-bootstrap/13657/18?u=sam"
     exit 1
   fi
 
@@ -257,18 +245,17 @@ check_prereqs() {
   folder=`$docker_path info --format '{{.DockerRootDir}}'`
   safe_folder=${folder:-/var/lib/docker}
   if [[ -d $safe_folder && $(stat -f --format="%a*%S" $safe_folder)/1024**3 -lt 5 ]] ; then
-    echo "OwO What's this? You need 5gb or more where the safe folder is to continue."
+    echo "You have less than 5GB of free space on the disk where $safe_folder is located. You will need more space to continue"
     df -h $safe_folder
     echo
     if tty >/dev/null; then
-      read -p "Would you like to attempt to recover space by cleaning docker images and containers in the system? (y/n)" -n 1 -r
+      read -p "Would you like to attempt to recover space by cleaning docker images and containers in the system? (y/N)" -n 1 -r
       echo
-      if [[ $REPLY =~ ^[Nn]$ ]]
+      if [[ $REPLY =~ ^[Yy]$ ]]
       then
-      echo "cweaning...."
         $docker_path container prune --force --filter until=24h >/dev/null
         $docker_path image prune --all --force --filter until=24h >/dev/null
-        echo "cweaned up!!"
+        echo "If the cleanup was successful, you may try again now"
       fi
     fi
     exit 1
@@ -276,12 +263,12 @@ check_prereqs() {
 
   # 8. container definition file is accessible and is not insecure (world-readable)
   if [[ ! -e "$config_file" || ! -r "$config_file" ]]; then
-    echo "ewwor!: $config_file does not exist or is not readable."
+    echo "ERROR: $config_file does not exist or is not readable."
     echo
     echo "Available configs ( `cd containers && ls -dm *.yml | tr -s '\n' ' ' | awk '{ gsub(/\.yml/, ""); print }'`)"
     exit 1
   elif [[ "$(find $config_file -perm -004)" ]]; then
-    echo "rawr!: $config_file fiwle is world-readable. You can secure this file by wunning: chmod o-rwx $config_file"
+    echo "WARNING: $config_file file is world-readable. You can secure this file by running: chmod o-rwx $config_file"
   fi
 }
 
@@ -343,13 +330,13 @@ set_template_info() {
          env.merge!(YAML.load(yml)['env'] || {})
        rescue Psych::SyntaxError => e
         puts e
-        puts "*ewwor!!"
+        puts "*ERROR."
        rescue => e
         puts yml
         p e
        end
     end
-    env.each{|k,v| puts "*ewwor!!" if v.is_a?(Hash)}
+    env.each{|k,v| puts "*ERROR." if v.is_a?(Hash)}
     puts env.map{|k,v| "-e\n#{k}=#{v}" }.join("\n")
 RUBY
 
@@ -372,7 +359,7 @@ RUBY
 
     if [ "$ok" -ne 1 ]; then
       echo "${env[@]}"
-      echo "YAML syntax error. pwease check your containers/*.yml config files."
+      echo "YAML syntax error. Please check your containers/*.yml config files."
       exit 1
     fi
 
@@ -388,7 +375,7 @@ RUBY
          labels.merge!(YAML.load(yml)['labels'] || {})
        rescue Psych::SyntaxError => e
         puts e
-        puts "*ewwor!!"
+        puts "*ERROR."
        rescue => e
         puts yml
         p e
@@ -407,7 +394,7 @@ RUBY
     labels=()
     ok=1
     while read i; do
-      if [ "$i" == "*ewwor!!" ]; then
+      if [ "$i" == "*ERROR." ]; then
         ok=0
       elif [ -n "$i" ]; then
         labels[${#labels[@]}]=$(echo $i | sed s/{{config}}/${config}/g)
@@ -416,7 +403,7 @@ RUBY
 
     if [ "$ok" -ne 1 ]; then
       echo "${labels[@]}"
-      echo "YAML syntax error. pwease check your containers/*.yml config files."
+      echo "YAML syntax error. Please check your containers/*.yml config files."
       exit 1
     fi
 
@@ -432,7 +419,7 @@ RUBY
          ports += (YAML.load(yml)['expose'] || [])
        rescue Psych::SyntaxError => e
         puts e
-        puts "*ewwor!!"
+        puts "*ERROR."
        rescue => e
         puts yml
         p e
@@ -451,7 +438,7 @@ RUBY
     ports=()
     ok=1
     while read i; do
-      if [ "$i" == "*ewwor!!" ]; then
+      if [ "$i" == "*ERROR." ]; then
         ok=0
       elif [ -n "$i" ]; then
         ports[${#ports[@]}]=$i
@@ -460,7 +447,7 @@ RUBY
 
     if [ "$ok" -ne 1 ]; then
       echo "${ports[@]}"
-      echo "YAML syntax error. pwease check your containers/*.yml config files."
+      echo "YAML syntax error. Please check your containers/*.yml config files."
       exit 1
     fi
 
@@ -478,9 +465,9 @@ fi
   if [ -d /var/discourse/shared/standalone/postgres_data_old ]; then
     echo
     echo "Old PostgreSQL backup data cluster detected taking up $(du -hs /var/discourse/shared/standalone/postgres_data_old | awk '{print $1}') detected"
-    read -p "Would you like to remove it?   OwO!   (y/N): " -n 1 -r && echo
+    read -p "Would you like to remove it? (y/N): " -n 1 -r && echo
 
-    if [[ $REPLY =~ ^[Nn]$ ]]; then
+    if [[ $REPLY =~ ^[Yy]$ ]]; then
       echo "removing old PostgreSQL data cluster at /var/discourse/shared/standalone/postgres_data_old..."
       rm -rf /var/discourse/shared/standalone/postgres_data_old*
     else
@@ -554,35 +541,6 @@ merge_user_args() {
 }
 
 run_start() {
-echo "
-   ___          ___  
-  / _ \__ __ __/ _ \ 
- | (_) \ V  V / (_) |
-  \___/ \_/\_/ \___/ 
-                     
- DISCOURSE ANIME EDITION
-        2013.
-"
-echo
-echo
-echo "STARTING..."
-
-echo "git bash run"
-
-echo
-echo
-echo "Running rake destroy:posts..."
-echo
-echo
-echo
-echo "COMPLETE"
-echo
-echo
-echo "Running rake destroy:users..."
-echo
-echo
-echo
-echo "COMPLETE"
 
    if [ -z "$START_CMD_ONLY" ]
    then
@@ -590,7 +548,7 @@ echo "COMPLETE"
      echo $existing
      if [ ! -z $existing ]
      then
-       echo "rawr! discourse is alweady wunning."
+       echo "Nothing to do, your container has already started!"
        exit 0
      fi
 
@@ -720,7 +678,6 @@ run_bootstrap() {
     $docker_path rm "$CONTAINER_ID"
     exit 77
   elif [[ $BOOTSTRAP_EXITCODE -gt 0 ]]; then
-  echo "rawr! you made a mistake senpai."
     echo "bootstrap failed with exit code $BOOTSTRAP_EXITCODE"
     echo "** FAILED TO BOOTSTRAP ** please scroll up and look for earlier error messages, there may be more than one."
     echo "./discourse-doctor may help diagnose the problem."
@@ -749,7 +706,7 @@ run_bootstrap() {
 case "$command" in
   bootstrap)
       run_bootstrap
-      echo "yay! successfuwy bootstrapped, to startup use ./launcher start $config"
+      echo "Successfully bootstrapped, to startup use ./launcher start $config"
       exit 0
       ;;
 
@@ -786,13 +743,11 @@ case "$command" in
     ;;
 
   start)
-  echo "rawr! starting..."
       run_start
       exit 0
       ;;
 
   rebuild)
-  echo "rawr! starting rebwild..."
       if [ "$(git symbolic-ref --short HEAD)" == "master" ]; then
         git branch -m master main
         git fetch origin
@@ -801,7 +756,32 @@ case "$command" in
       fi
 
       if [ "$(git symbolic-ref --short HEAD)" == "main" ]; then
-        echo "lol i deleted update code you suck"
+        echo "Ensuring launcher is up to date"
+
+        git remote update
+
+        LOCAL=$(git rev-parse HEAD)
+        REMOTE=$(git rev-parse @{u})
+        BASE=$(git merge-base HEAD @{u})
+
+        if [ $LOCAL = $REMOTE ]; then
+          echo "Launcher is up-to-date"
+
+        elif [ $LOCAL = $BASE ]; then
+          echo "Updating Launcher..."
+          git pull || (echo 'failed to update' && exit 1)
+
+          echo "Launcher updated, restarting..."
+          exec "$0" "${SAVED_ARGV[@]}"
+
+        elif [ $REMOTE = $BASE ]; then
+          echo "Your version of Launcher is ahead of origin"
+
+        else
+          echo "Launcher has diverged source, this is only expected in Dev mode"
+        fi
+
+      fi
 
       set_existing_container
 
@@ -827,10 +807,13 @@ case "$command" in
 
       run_start
       exit 0
+      ;;
 
 
-  destroy
+  destroy)
       (set -x; $docker_path stop -t 10 $config && $docker_path rm $config) || (echo "$config was not found" && exit 0)
       exit 0
+      ;;
+esac
 
 usage
